export enum AuditAction {
  AuthRegistered = 'AUTH_REGISTERED',
  AuthEmailVerified = 'AUTH_EMAIL_VERIFIED',
  AuthVerificationCodeResent = 'AUTH_VERIFICATION_CODE_RESENT',
  AuthLoginSucceeded = 'AUTH_LOGIN_SUCCEEDED',
  AuthLoginFailed = 'AUTH_LOGIN_FAILED',
  AuthPasswordResetRequested = 'AUTH_PASSWORD_RESET_REQUESTED',
  AuthPasswordResetCompleted = 'AUTH_PASSWORD_RESET_COMPLETED',
  AuthSessionRefreshed = 'AUTH_SESSION_REFRESHED',
  AuthLoggedOut = 'AUTH_LOGGED_OUT',
  DriverApplicationSubmitted = 'DRIVER_APPLICATION_SUBMITTED',
  DriverApplicationApproved = 'DRIVER_APPLICATION_APPROVED',
  DriverApplicationRejected = 'DRIVER_APPLICATION_REJECTED',
  TripCreated = 'TRIP_CREATED',
  TripPublished = 'TRIP_PUBLISHED',
  TripStarted = 'TRIP_STARTED',
  TripCompleted = 'TRIP_COMPLETED',
  TripCancelled = 'TRIP_CANCELLED',
  ReportCreated = 'REPORT_CREATED',
  ReportReviewed = 'REPORT_REVIEWED',
  SanctionApplied = 'SANCTION_APPLIED',
  SanctionExpired = 'SANCTION_EXPIRED',
  SanctionAppealSubmitted = 'SANCTION_APPEAL_SUBMITTED',
  SanctionAppealApproved = 'SANCTION_APPEAL_APPROVED',
  SanctionAppealRejected = 'SANCTION_APPEAL_REJECTED',
  SanctionLiftedManually = 'SANCTION_LIFTED_MANUALLY',
}

export enum AuditEntityType {
  User = 'USER',
  UserMembership = 'USER_MEMBERSHIP',
  DriverProfile = 'DRIVER_PROFILE',
  Trip = 'TRIP',
  Report = 'REPORT',
  OperationalSanction = 'OPERATIONAL_SANCTION',
  SanctionAppeal = 'SANCTION_APPEAL',
  AuthSession = 'AUTH_SESSION',
}
